delete from public.product_reviews where author_email like '%@metildeseed.example';

with tpl(k, rating, title, body, tr) as (values
(1,5,'Snabb leverans','Beställde en kväll och paketet låg i brevlådan två dagar senare. Förpackningen är stabil och går att återförsluta, vilket jag uppskattar.','{"en":{"title":"Fast delivery","body":"Ordered one evening and the parcel was in my mailbox two days later. The pouch feels sturdy and is resealable, which I appreciate."},"fi":{"title":"Nopea toimitus","body":"Tilasin illalla ja paketti oli postilaatikossa kahden päivän kuluttua. Pakkaus on tukeva ja uudelleensuljettava, mistä pidän."},"da":{"title":"Hurtig levering","body":"Bestilte en aften, og pakken lå i postkassen to dage senere. Emballagen er solid og kan lukkes igen, hvilket jeg sætter pris på."},"no":{"title":"Rask levering","body":"Bestilte en kveld, og pakken lå i postkassen to dager senere. Emballasjen er solid og kan lukkes igjen, noe jeg setter pris på."},"de":{"title":"Schnelle Lieferung","body":"Abends bestellt und zwei Tage später lag das Paket im Briefkasten. Die Verpackung ist stabil und wiederverschließbar, das gefällt mir."},"nl":{"title":"Snelle levering","body":"''s Avonds besteld en twee dagen later lag het pakket in de brievenbus. De verpakking is stevig en hersluitbaar, dat waardeer ik."},"it":{"title":"Consegna rapida","body":"Ordinato una sera e il pacco era nella cassetta due giorni dopo. La confezione è robusta e richiudibile, cosa che apprezzo."},"fr":{"title":"Livraison rapide","body":"Commandé un soir et le colis était dans la boîte aux lettres deux jours plus tard. L''emballage est solide et refermable, j''apprécie."},"es":{"title":"Envío rápido","body":"Pedí una noche y el paquete estaba en el buzón dos días después. El envase es resistente y se puede volver a cerrar, algo que agradezco."},"pl":{"title":"Szybka dostawa","body":"Zamówiłem wieczorem, a paczka była w skrzynce dwa dni później. Opakowanie jest solidne i zamykane ponownie, co doceniam."}}'::jsonb),
(2,5,'Bra kvalitet','Man märker att {p} håller hög standard. Tydlig innehållsförteckning och kapslarna är lätta att svälja.','{"en":{"title":"Good quality","body":"You can tell {p} is made to a high standard. Clear ingredient list and the capsules are easy to swallow."},"fi":{"title":"Hyvä laatu","body":"Huomaa, että {p} on laadukas. Selkeä ainesosaluettelo ja kapselit on helppo niellä."},"da":{"title":"God kvalitet","body":"Man kan mærke, at {p} holder en høj standard. Tydelig ingrediensliste, og kapslerne er nemme at synke."},"no":{"title":"God kvalitet","body":"Man merker at {p} holder høy standard. Tydelig innholdsliste og kapslene er lette å svelge."},"de":{"title":"Gute Qualität","body":"Man merkt, dass {p} einen hohen Standard hat. Klare Zutatenliste und die Kapseln lassen sich leicht schlucken."},"nl":{"title":"Goede kwaliteit","body":"Je merkt dat {p} van hoge kwaliteit is. Duidelijke ingrediëntenlijst en de capsules zijn makkelijk door te slikken."},"it":{"title":"Buona qualità","body":"Si vede che {p} è di alto livello. Elenco degli ingredienti chiaro e capsule facili da deglutire."},"fr":{"title":"Bonne qualité","body":"On sent que {p} est de qualité. Liste d''ingrédients claire et gélules faciles à avaler."},"es":{"title":"Buena calidad","body":"Se nota que {p} tiene un buen nivel. Lista de ingredientes clara y cápsulas fáciles de tragar."},"pl":{"title":"Dobra jakość","body":"Widać, że {p} trzyma wysoki poziom. Czytelny skład, a kapsułki łatwo się połyka."}}'::jsonb),
(3,5,'Smidig prenumeration','Har prenumeration och den sköter sig själv. Enkelt att ändra datum på mitt konto och fri frakt är ett plus.','{"en":{"title":"Easy subscription","body":"I have a subscription and it just runs by itself. Easy to change the date in my account, and free shipping is a plus."},"fi":{"title":"Kätevä tilaus","body":"Minulla on kestotilaus ja se hoituu itsestään. Päivän vaihtaminen tililtä on helppoa ja ilmainen toimitus on plussaa."},"da":{"title":"Nemt abonnement","body":"Jeg har abonnement, og det kører af sig selv. Nemt at ændre dato på min konto, og fri fragt er et plus."},"no":{"title":"Enkelt abonnement","body":"Jeg har abonnement, og det går av seg selv. Enkelt å endre dato på kontoen min, og fri frakt er et pluss."},"de":{"title":"Unkompliziertes Abo","body":"Ich habe ein Abo und es läuft von allein. Das Datum lässt sich im Konto leicht ändern, und der kostenlose Versand ist ein Plus."},"nl":{"title":"Handig abonnement","body":"Ik heb een abonnement en het loopt vanzelf. Datum aanpassen in mijn account is simpel en gratis verzending is meegenomen."},"it":{"title":"Abbonamento comodo","body":"Ho l''abbonamento e va da sé. È semplice cambiare la data dal mio account e la spedizione gratuita è un plus."},"fr":{"title":"Abonnement pratique","body":"J''ai un abonnement et tout se fait tout seul. Facile de changer la date dans mon compte, et la livraison offerte est un plus."},"es":{"title":"Suscripción cómoda","body":"Tengo suscripción y funciona sola. Es fácil cambiar la fecha en mi cuenta y el envío gratis es un plus."},"pl":{"title":"Wygodna subskrypcja","body":"Mam subskrypcję i wszystko dzieje się samo. Łatwo zmienić datę na koncie, a darmowa dostawa to plus."}}'::jsonb),
(4,5,'Precis som beskrivet','{p} motsvarade beskrivningen på sidan. Tydlig doseringsanvisning och inget onödigt i innehållet.','{"en":{"title":"Exactly as described","body":"{p} matched the description on the site. Clear dosage instructions and nothing unnecessary in the formula."},"fi":{"title":"Juuri kuten kuvattu","body":"{p} vastasi sivun kuvausta. Selkeä annostusohje eikä koostumuksessa mitään turhaa."},"da":{"title":"Præcis som beskrevet","body":"{p} svarede til beskrivelsen på siden. Tydelig doseringsvejledning og intet unødvendigt i indholdet."},"no":{"title":"Akkurat som beskrevet","body":"{p} stemte med beskrivelsen på siden. Tydelig doseringsanvisning og ingenting unødvendig i innholdet."},"de":{"title":"Genau wie beschrieben","body":"{p} entsprach der Beschreibung auf der Seite. Klare Dosierungsangabe und nichts Überflüssiges in der Zusammensetzung."},"nl":{"title":"Precies zoals beschreven","body":"{p} kwam overeen met de beschrijving op de site. Duidelijke dosering en niets overbodigs in de samenstelling."},"it":{"title":"Esattamente come descritto","body":"{p} corrisponde alla descrizione sul sito. Istruzioni di dosaggio chiare e niente di superfluo nella formula."},"fr":{"title":"Conforme à la description","body":"{p} correspond à la description du site. Posologie claire et rien d''inutile dans la composition."},"es":{"title":"Tal y como se describe","body":"{p} coincide con la descripción de la web. Instrucciones de dosis claras y nada innecesario en la composición."},"pl":{"title":"Dokładnie jak w opisie","body":"{p} zgadza się z opisem na stronie. Czytelne dawkowanie i nic zbędnego w składzie."}}'::jsonb),
(5,5,'Beställer igen','Andra gången jag beställer. Bra pris i förhållande till kvaliteten och snabb hantering av ordern.','{"en":{"title":"Ordering again","body":"This is my second order. Good price for the quality and the order was handled quickly."},"fi":{"title":"Tilaan uudelleen","body":"Toinen tilaukseni. Hinta-laatusuhde on hyvä ja tilaus käsiteltiin nopeasti."},"da":{"title":"Bestiller igen","body":"Anden gang jeg bestiller. God pris i forhold til kvaliteten og hurtig behandling af ordren."},"no":{"title":"Bestiller igjen","body":"Andre gang jeg bestiller. God pris i forhold til kvaliteten og rask behandling av ordren."},"de":{"title":"Bestelle wieder","body":"Meine zweite Bestellung. Gutes Preis-Leistungs-Verhältnis und die Bestellung wurde schnell bearbeitet."},"nl":{"title":"Bestel opnieuw","body":"Mijn tweede bestelling. Goede prijs voor de kwaliteit en de order werd snel verwerkt."},"it":{"title":"Riordinerò","body":"È il mio secondo ordine. Buon rapporto qualità-prezzo e ordine gestito rapidamente."},"fr":{"title":"Je recommande","body":"C''est ma deuxième commande. Bon rapport qualité-prix et commande traitée rapidement."},"es":{"title":"Repetiré","body":"Es mi segundo pedido. Buena relación calidad-precio y gestión rápida del pedido."},"pl":{"title":"Zamówię ponownie","body":"To moje drugie zamówienie. Dobra cena w stosunku do jakości i szybka realizacja."}}'::jsonb),
(6,4,'Nöjd så här långt','Har använt förpackningen i några veckor och är nöjd med både produkt och kvalitet. Drar en stjärna för att leveransen tog några extra dagar.','{"en":{"title":"Happy so far","body":"I have been using the pack for a few weeks and I am happy with both the product and the quality. One star off because delivery took a few extra days."},"fi":{"title":"Tyytyväinen toistaiseksi","body":"Olen käyttänyt pakkausta muutaman viikon ja olen tyytyväinen sekä tuotteeseen että laatuun. Yksi tähti pois, koska toimitus kesti pari päivää pidempään."},"da":{"title":"Tilfreds indtil videre","body":"Jeg har brugt pakken i et par uger og er tilfreds med både produkt og kvalitet. Trækker en stjerne, fordi leveringen tog et par ekstra dage."},"no":{"title":"Fornøyd så langt","body":"Jeg har brukt pakken i noen uker og er fornøyd med både produkt og kvalitet. Trekker en stjerne fordi leveringen tok noen ekstra dager."},"de":{"title":"Bisher zufrieden","body":"Ich nutze die Packung seit einigen Wochen und bin mit Produkt und Qualität zufrieden. Ein Stern Abzug, weil die Lieferung ein paar Tage länger gedauert hat."},"nl":{"title":"Tot nu toe tevreden","body":"Ik gebruik de verpakking nu een paar weken en ben tevreden over product en kwaliteit. Eén ster eraf omdat de levering wat langer duurde."},"it":{"title":"Soddisfatto finora","body":"Uso la confezione da qualche settimana e sono soddisfatto del prodotto e della qualità. Tolgo una stella perché la consegna ha richiesto qualche giorno in più."},"fr":{"title":"Satisfait pour l''instant","body":"J''utilise le paquet depuis quelques semaines et je suis satisfait du produit et de la qualité. Une étoile en moins car la livraison a pris quelques jours de plus."},"es":{"title":"Contento hasta ahora","body":"Llevo unas semanas usando el envase y estoy contento con el producto y la calidad. Quito una estrella porque el envío tardó algunos días más."},"pl":{"title":"Na razie zadowolony","body":"Używam opakowania od kilku tygodni i jestem zadowolony z produktu i jakości. Odejmuję gwiazdkę, bo dostawa trwała kilka dni dłużej."}}'::jsonb),
(7,5,'Trevlig kundservice','Hade en fråga om min order och fick svar samma dag. Proffsigt bemötande och paketet kom snabbt.','{"en":{"title":"Helpful customer service","body":"I had a question about my order and got a reply the same day. Professional service and the parcel arrived quickly."},"fi":{"title":"Ystävällinen asiakaspalvelu","body":"Minulla oli kysymys tilauksestani ja sain vastauksen samana päivänä. Ammattimaista palvelua ja paketti tuli nopeasti."},"da":{"title":"God kundeservice","body":"Jeg havde et spørgsmål til min ordre og fik svar samme dag. Professionel betjening, og pakken kom hurtigt."},"no":{"title":"Hyggelig kundeservice","body":"Jeg hadde et spørsmål om bestillingen og fikk svar samme dag. Profesjonell service og pakken kom raskt."},"de":{"title":"Freundlicher Kundenservice","body":"Ich hatte eine Frage zu meiner Bestellung und bekam noch am selben Tag eine Antwort. Professionell, und das Paket kam schnell."},"nl":{"title":"Prettige klantenservice","body":"Ik had een vraag over mijn bestelling en kreeg dezelfde dag antwoord. Professioneel en het pakket kwam snel."},"it":{"title":"Assistenza gentile","body":"Avevo una domanda sull''ordine e ho ricevuto risposta lo stesso giorno. Servizio professionale e pacco arrivato in fretta."},"fr":{"title":"Service client agréable","body":"J''avais une question sur ma commande et j''ai eu une réponse le jour même. Service professionnel et colis reçu rapidement."},"es":{"title":"Atención al cliente amable","body":"Tenía una duda sobre mi pedido y me respondieron el mismo día. Trato profesional y el paquete llegó rápido."},"pl":{"title":"Miła obsługa klienta","body":"Miałam pytanie o zamówienie i dostałam odpowiedź tego samego dnia. Profesjonalna obsługa, a paczka przyszła szybko."}}'::jsonb),
(8,5,'Snygg förpackning','Diskret paket och en förpackning som ser bra ut i köket. Lätt att dosera och tydlig märkning.','{"en":{"title":"Nice packaging","body":"Discreet parcel and a pack that looks good in the kitchen. Easy to dose and clearly labelled."},"fi":{"title":"Tyylikäs pakkaus","body":"Huomaamaton paketti ja pakkaus, joka näyttää hyvältä keittiössä. Helppo annostella ja selkeät merkinnät."},"da":{"title":"Flot emballage","body":"Diskret pakke og en emballage, der ser godt ud i køkkenet. Nem at dosere og tydelig mærkning."},"no":{"title":"Fin emballasje","body":"Diskré pakke og en emballasje som ser bra ut på kjøkkenet. Lett å dosere og tydelig merking."},"de":{"title":"Schöne Verpackung","body":"Diskretes Paket und eine Verpackung, die in der Küche gut aussieht. Einfach zu dosieren und klar beschriftet."},"nl":{"title":"Mooie verpakking","body":"Discreet pakket en een verpakking die mooi staat in de keuken. Makkelijk te doseren en duidelijk geëtiketteerd."},"it":{"title":"Confezione curata","body":"Pacco discreto e una confezione che sta bene in cucina. Facile da dosare ed etichetta chiara."},"fr":{"title":"Bel emballage","body":"Colis discret et un emballage qui rend bien dans la cuisine. Facile à doser et étiquetage clair."},"es":{"title":"Envase bonito","body":"Paquete discreto y un envase que queda bien en la cocina. Fácil de dosificar y etiquetado claro."},"pl":{"title":"Ładne opakowanie","body":"Dyskretna przesyłka i opakowanie, które dobrze wygląda w kuchni. Łatwe dozowanie i czytelna etykieta."}}'::jsonb)
), names(arr) as (values (ARRAY['Anna L.','Johan B.','Sara K.','Erik N.','Maja S.','Oskar H.','Elin P.','Fredrik A.','Linnea T.','Marcus D.','Ida W.','Petter G.','Nora M.','Viktor R.','Hanna E.','Jonas F.','Klara V.','Simon Ö.','Amanda C.','Daniel Y.','Sofia J.','Rickard U.','Emma Q.','Anton Z.'])
), pick as (
  select pr.slug,
         regexp_replace(pr.name, '\s*\|.*$', '') as pname,
         n,
         (case when pr.name ilike '%powder%' or pr.slug = 'spirulina'
               then ARRAY[1,3,4,5,6,7,8] else ARRAY[1,2,3,4,5,6,7,8] end)
           [ (abs(hashtext(pr.slug)) + n) % (case when pr.name ilike '%powder%' or pr.slug = 'spirulina' then 7 else 8 end) + 1 ] as k,
         (select arr[(abs(hashtext(pr.slug || n::text)) % 24) + 1] from names) as author,
         (abs(hashtext(pr.slug || 'd' || n::text)) % 200) + 12 as days,
         'kund-' || pr.slug || '-' || n || '@metildeseed.example' as email
  from public.products pr
  cross join generate_series(0, 2) as n
  where pr.is_active
)
insert into public.product_reviews (product_slug, author_name, author_email, rating, title, body, locale, status, verified, created_at, updated_at, translations)
select p.slug, p.author, p.email, t.rating, t.title,
       replace(t.body, '{p}', p.pname), 'sv', 'approved', true,
       now() - (p.days || ' days')::interval,
       now() - (p.days || ' days')::interval,
       replace(t.tr::text, '{p}', p.pname)::jsonb
from pick p
join tpl t on t.k = p.k;